"""Add missing tables

Revision ID: 431f56828918
Revises: 5d67e80d47b7
Create Date: 2026-09-13 20:02:18.689081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431f56828918'
down_revision: Union[str, Sequence[str], None] = '5d67e80d47b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pathogen_id', sa.Integer(), nullable=True),
    sa.Column('antimicrobial_id', sa.Integer(), nullable=True),
    sa.Column('condition_expression', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='ruleseverity'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['antimicrobial_id'], ['antimicrobials.id'], ),
    sa.ForeignKeyConstraint(['pathogen_id'], ['pathogens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_rules_id'), 'clinical_rules', ['id'], unique=False)
    op.create_table('cell_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_result_id', sa.Integer(), nullable=False),
    sa.Column('rbc_count', sa.Float(), nullable=True),
    sa.Column('wbc_count', sa.Float(), nullable=True),
    sa.Column('platelet_count', sa.Float(), nullable=True),
    sa.Column('hemoglobin_level', sa.Float(), nullable=True),
    sa.Column('hematocrit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cell_counts_id'), 'cell_counts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cell_counts_id'), table_name='cell_counts')
    op.drop_table('cell_counts')
    op.drop_index(op.f('ix_clinical_rules_id'), table_name='clinical_rules')
    op.drop_table('clinical_rules')
    # ### end Alembic commands ###
