"""alter analysis table

Revision ID: 4c4dc5dffa17
Revises: 040b820888e5
Create Date: 2026-09-16 10:31:41.941876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4dc5dffa17'
down_revision: Union[str, Sequence[str], None] = '040b820888e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_analysis_results_visit_id'), table_name='analysis_results')
    op.create_index(op.f('ix_analysis_results_patient_id'), 'analysis_results', ['patient_id'], unique=False)
    op.drop_constraint(op.f('analysis_results_visit_id_fkey'), 'analysis_results', type_='foreignkey')
    op.drop_constraint(op.f('analysis_results_pathogen_id_fkey'), 'analysis_results', type_='foreignkey')
    op.create_foreign_key(None, 'analysis_results', 'patients', ['patient_id'], ['id'], ondelete='SET NULL')
    op.drop_column('analysis_results', 'pathogen_id')
    op.drop_column('analysis_results', 'visit_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('visit_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('analysis_results', sa.Column('pathogen_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'analysis_results', type_='foreignkey')
    op.create_foreign_key(op.f('analysis_results_pathogen_id_fkey'), 'analysis_results', 'pathogens', ['pathogen_id'], ['id'])
    op.create_foreign_key(op.f('analysis_results_visit_id_fkey'), 'analysis_results', 'clinical_visits', ['visit_id'], ['id'])
    op.drop_index(op.f('ix_analysis_results_patient_id'), table_name='analysis_results')
    op.create_index(op.f('ix_analysis_results_visit_id'), 'analysis_results', ['visit_id'], unique=False)
    op.drop_column('analysis_results', 'patient_id')
    # ### end Alembic commands ###
