"""add roles table

Revision ID: 84d4f40ab3e1
Revises: 7c1a2f4e9b10
Create Date: 2026-09-15 10:10:48.799383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84d4f40ab3e1'
down_revision: Union[str, Sequence[str], None] = '7c1a2f4e9b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_id'), 'user_role', ['id'], unique=False)
    op.drop_index(op.f('ix_cell_counts_id'), table_name='cell_counts')
    op.drop_table('cell_counts')
    op.drop_index(op.f('ix_clinical_rules_id'), table_name='clinical_rules')
    op.drop_table('clinical_rules')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('DOCTOR', 'LAB_TECHNICIAN', 'ADMIN', name='userrole'), autoincrement=False, nullable=False))
    op.create_table('clinical_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pathogen_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('antimicrobial_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('condition_expression', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('severity', postgresql.ENUM('INFO', 'WARNING', 'CRITICAL', name='ruleseverity'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['antimicrobial_id'], ['antimicrobials.id'], name=op.f('clinical_rules_antimicrobial_id_fkey')),
    sa.ForeignKeyConstraint(['pathogen_id'], ['pathogens.id'], name=op.f('clinical_rules_pathogen_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('clinical_rules_pkey'))
    )
    op.create_index(op.f('ix_clinical_rules_id'), 'clinical_rules', ['id'], unique=False)
    op.create_table('cell_counts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('analysis_result_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rbc_count', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('wbc_count', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('platelet_count', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hemoglobin_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hematocrit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], name=op.f('cell_counts_analysis_result_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cell_counts_pkey'))
    )
    op.create_index(op.f('ix_cell_counts_id'), 'cell_counts', ['id'], unique=False)
    op.drop_index(op.f('ix_user_role_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_table('role')
    # ### end Alembic commands ###
